import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Drink {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //The liters content of water
  final double liters;

  //When the drink occured
  final DateTime dateTime;

  //Default constructor
  Drink(this.id, this.liters, this.dateTime);
}//Drink